// card_nav.js — GENERATED by build_card_nav.js. Do not edit by hand;
// re-run `node build_card_nav.js` from the repo root instead.
//
// Adds a previous/next strip under a task card when a student views it on
// screen. Deliberately inert in three cases:
//   1. inside an iframe  — the review console renders cards in one, and extra
//      DOM would shift every blockIndex the feedback JSON records;
//   2. print media       — the PDF/HTML build renders with emulateMediaType
//      ('print'), so bundles stay exactly as they were;
//   3. @media print      — a student printing from the browser gets clean paper.
// It also mounts outside the dc React root, so a setState re-render (checkbox,
// choice) cannot drop it.
(function () {
  'use strict';
  if (window.self !== window.top) return;
  try { if (window.matchMedia && window.matchMedia('print').matches) return; } catch (e) {}

  var NAV = {"P7_T1_M1_meet_the_cam_he.dc.html":{"prev":null,"next":"P7_T1_M2_upload_camera_sketch_he.dc.html"},"P7_T1_M2_upload_camera_sketch_he.dc.html":{"prev":"P7_T1_M1_meet_the_cam_he.dc.html","next":"P7_T1_M3_first_stream_he.dc.html"},"P7_T1_M3_first_stream_he.dc.html":{"prev":"P7_T1_M2_upload_camera_sketch_he.dc.html","next":"P7_T1_M4_mount_camera_he.dc.html"},"P7_T1_M4_mount_camera_he.dc.html":{"prev":"P7_T1_M3_first_stream_he.dc.html","next":"P7_T1_M5_power_rail_he.dc.html"},"P7_T1_M5_power_rail_he.dc.html":{"prev":"P7_T1_M4_mount_camera_he.dc.html","next":"P7_T1_M6_wire_motors_he.dc.html"},"P7_T1_M6_wire_motors_he.dc.html":{"prev":"P7_T1_M5_power_rail_he.dc.html","next":"P7_T1_M7_drive_from_page_he.dc.html"},"P7_T1_M7_drive_from_page_he.dc.html":{"prev":"P7_T1_M6_wire_motors_he.dc.html","next":"P7_T1_M8_drive_by_video_he.dc.html"},"P7_T1_M8_drive_by_video_he.dc.html":{"prev":"P7_T1_M7_drive_from_page_he.dc.html","next":"P7_T1_M9_exploration_celebrate_he.dc.html"},"P7_T1_M9_exploration_celebrate_he.dc.html":{"prev":"P7_T1_M8_drive_by_video_he.dc.html","next":null},"P7_T2_M1_startup_he.dc.html":{"prev":null,"next":"P7_T2_M2_explorer_identity_he.dc.html"},"P7_T2_M2_explorer_identity_he.dc.html":{"prev":"P7_T2_M1_startup_he.dc.html","next":"P7_T2_M3_speed_profile_he.dc.html"},"P7_T2_M3_speed_profile_he.dc.html":{"prev":"P7_T2_M2_explorer_identity_he.dc.html","next":"P7_T2_M4_page_design_he.dc.html"},"P7_T2_M4_page_design_he.dc.html":{"prev":"P7_T2_M3_speed_profile_he.dc.html","next":"P7_T2_M5_interface_with_claude_he.dc.html"},"P7_T2_M5_interface_with_claude_he.dc.html":{"prev":"P7_T2_M4_page_design_he.dc.html","next":"P7_T2_M6_design_mission_he.dc.html"},"P7_T2_M6_design_mission_he.dc.html":{"prev":"P7_T2_M5_interface_with_claude_he.dc.html","next":"P7_T2_M7_signature_exploration_he.dc.html"},"P7_T2_M7_signature_exploration_he.dc.html":{"prev":"P7_T2_M6_design_mission_he.dc.html","next":null}};
  var LBL = {"P7_T1_M1_meet_the_cam_he.dc.html":{"title":"מכירים את מצלמת ה-ESP32","label":"שלב 1"},"P7_T1_M2_upload_camera_sketch_he.dc.html":{"title":"מעלים את קוד הסייר","label":"שלב 2"},"P7_T1_M3_first_stream_he.dc.html":{"title":"השידור הראשון","label":"שלב 3"},"P7_T1_M4_mount_camera_he.dc.html":{"title":"מרכיבים את המצלמה על המכונית","label":"שלב 4"},"P7_T1_M5_power_rail_he.dc.html":{"title":"מסילת חשמל נפרדת למצלמה","label":"שלב 5"},"P7_T1_M6_wire_motors_he.dc.html":{"title":"ארבעה חוטים למנועים","label":"שלב 6"},"P7_T1_M7_drive_from_page_he.dc.html":{"title":"נוהגים ורואים","label":"שלב 7"},"P7_T1_M8_drive_by_video_he.dc.html":{"title":"נוהגים לפי הווידאו בלבד","label":"שלב 8"},"P7_T1_M9_exploration_celebrate_he.dc.html":{"title":"משימת סיור — ומסיימים בגדול","label":"שלב 9"},"P7_T2_M1_startup_he.dc.html":{"title":"הפעלה מרוכזת","label":"שלב 1"},"P7_T2_M2_explorer_identity_he.dc.html":{"title":"נותנים לסייר שם","label":"שלב 2"},"P7_T2_M3_speed_profile_he.dc.html":{"title":"בוחרים פרופיל מהירות","label":"שלב 3"},"P7_T2_M4_page_design_he.dc.html":{"title":"מעצבים את דף הסיור","label":"שלב 4"},"P7_T2_M5_interface_with_claude_he.dc.html":{"title":"משנים את הממשק עם קלוד קוד","label":"שלב 5"},"P7_T2_M6_design_mission_he.dc.html":{"title":"מתכננים משימת סיור","label":"שלב 6"},"P7_T2_M7_signature_exploration_he.dc.html":{"title":"סיור חתימה","label":"שלב 7"}};

  var file = '';
  try { file = decodeURIComponent(location.pathname.split('/').pop() || ''); } catch (e) { return; }
  var entry = NAV[file];
  if (!entry) return;

  function resolve(spec) {
    if (!spec) return null;
    if (typeof spec === 'string') return spec;
    var v = null;
    try { v = localStorage.getItem(spec.k); } catch (e) {}
    return (v && spec.m[v]) ? spec.m[v] : spec.d;
  }

  var prev = resolve(entry.prev);
  var next = resolve(entry.next);
  if (!prev && !next) return;

  function chip(target, kind) {
    var meta = LBL[target] || {};
    var a = document.createElement('a');
    a.className = 'cn-chip ' + (kind === 'next' ? 'cn-nx' : 'cn-pv');
    a.href = './' + target;
    var k = document.createElement('span');
    k.className = 'cn-k';
    var word = document.createElement('span');
    word.textContent = kind === 'next' ? 'הכרטיסייה הבאה' : 'הכרטיסייה הקודמת';
    var arrow = document.createElement('span');
    arrow.className = 'cn-a';
    arrow.textContent = kind === 'next' ? '\u2190' : '\u2192';
    if (kind === 'next') { k.appendChild(word); k.appendChild(arrow); }
    else { k.appendChild(arrow); k.appendChild(word); }
    var t = document.createElement('span');
    t.className = 'cn-t';
    t.textContent = [meta.label, meta.title].filter(Boolean).join(' · ');
    a.appendChild(k);
    a.appendChild(t);
    return a;
  }

  function mount() {
    if (document.getElementById('card-nav-root')) return;
    var css = document.createElement('style');
    css.textContent =
      '#card-nav-root{background:oklch(0.972 0.008 85);padding:0 20px 44px;display:flex;' +
      'justify-content:center;font-family:Rubik,sans-serif;}' +
      '#card-nav-root .cn-bar{width:100%;max-width:760px;display:flex;gap:14px;align-items:stretch;}' +
      '#card-nav-root .cn-chip{flex:1 1 0;display:flex;flex-direction:column;gap:4px;' +
      'text-decoration:none;background:#fff;border:1px solid oklch(0.9 0.006 85);border-radius:14px;' +
      'padding:13px 17px;box-shadow:0 1px 2px rgba(40,35,20,0.04);' +
      'transition:border-color .15s ease,box-shadow .15s ease;}' +
      '#card-nav-root .cn-chip:hover{border-color:oklch(0.62 0.1 248);' +
      'box-shadow:0 6px 18px -10px rgba(40,35,20,0.35);}' +
      '#card-nav-root .cn-pv{align-items:flex-start;}' +
      '#card-nav-root .cn-nx{align-items:flex-end;text-align:end;}' +
      '#card-nav-root .cn-gap{flex:1 1 0;}' +
      '#card-nav-root .cn-k{display:flex;align-items:center;gap:7px;font-size:12.5px;' +
      'font-weight:600;color:oklch(0.55 0.012 260);}' +
      '#card-nav-root .cn-a{font-size:15px;color:oklch(0.55 0.09 248);}' +
      '#card-nav-root .cn-t{font-size:15px;font-weight:700;line-height:1.35;' +
      'color:oklch(0.42 0.11 248);}' +
      '@media print{#card-nav-root{display:none !important;}}';
    document.head.appendChild(css);

    var root = document.createElement('div');
    root.id = 'card-nav-root';
    root.setAttribute('dir', 'rtl');
    var bar = document.createElement('nav');
    bar.className = 'cn-bar';
    bar.setAttribute('aria-label', 'ניווט בין כרטיסיות');
    // DOM order is prev-then-next; in RTL that puts הקודמת on the right.
    if (prev) bar.appendChild(chip(prev, 'prev'));
    else { var g1 = document.createElement('span'); g1.className = 'cn-gap'; bar.appendChild(g1); }
    if (next) bar.appendChild(chip(next, 'next'));
    else { var g2 = document.createElement('span'); g2.className = 'cn-gap'; bar.appendChild(g2); }
    root.appendChild(bar);
    document.body.appendChild(root);
  }

  // Wait for the dc runtime to paint the card so the strip lands under it.
  var t0 = Date.now();
  (function wait() {
    if (document.querySelector('.tc-page') || Date.now() - t0 > 4000) { mount(); return; }
    setTimeout(wait, 60);
  })();
})();
