// build_card_nav.js — generate the per-project card_nav.js navigation runtime
// and make sure every HE task card loads it.
//
// Usage:  node build_card_nav.js          (writes files)
//         node build_card_nav.js --check  (verify only, non-zero exit on drift)
//
// WHY A GENERATOR: the prev/next chain is derived from the card filenames
// (P<n>_T<tier>_M<milestone>), so adding or renaming a card only requires a
// re-run — there is no hand-maintained list inside 55 separate cards. The only
// hand-declared data is BRANCHES below, because a branch depends on a runtime
// choice the student made, which filenames cannot express.
//
// Re-run this after adding/renaming/retitling a task card.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, 'Arduino_Projects');
const PROJECTS = [
  'Project_1_Light_Signals',
  'Project_2_Reaction_Time_Game',
  'Project_3_Dont_Get_Too_Close',
  'Project_4_Line_Following_Car',
  'Project_5_Remote_Controlled_Car',
  'Project_6_ESP32_WiFi_Controller',
  'Project_7_Camera_Explorer',
  'Project_8_Tiny_Quadcopter',
];

// Branch points: a card whose NEXT depends on the pattern/mode the student
// picked, stored in localStorage by that card's own DCLogic.
//   options — per choice value, the wiring card it routes through, or null to
//   skip straight to the card after the branch block.
// "Not chosen yet" routes to the FIRST option card, which opens with its own
// "you can skip this if you chose X" notice — so a student who lands there
// wrongly is corrected on arrival, whereas one who skips wiring by accident
// is not.
const BRANCHES = {
  'T2_M2_pick_pattern_he.dc.html': {
    key: 'tc_p1t2m2_choice',
    options: {
      A: 'T2_M2a_wire_second_led_he.dc.html',
      B: 'T2_M2b_wire_third_led_he.dc.html',
      C: null,
    },
  },
  'P2_T2_M2_pick_feedback_mode_he.dc.html': {
    key: 'tc_p2t2m2_choice',
    options: {
      A: 'P2_T2_M2b_wire_three_leds_he.dc.html',
      B: null,
      C: null,
    },
  },
};

const stripEmoji = (s) =>
  s.replace(/^[\s -㌀\uD83C-􏰀-\uDFFF️‍]+/, '').trim();

// "T2_M2b_wire_third_led_he.dc.html" -> {tier:2, num:2, sub:2}
// sub: '' = the milestone card itself, 'a' = 1, 'b' = 2 (optional branch cards)
function parseName(file) {
  const m = file.match(/^(?:P(\d)_)?T(\d)_M(\d+)([ab]?)_/);
  if (!m) return null;
  return { tier: Number(m[2]), num: Number(m[3]), sub: m[4] ? m[4].charCodeAt(0) - 96 : 0 };
}

function cardMeta(dir, file) {
  const src = fs.readFileSync(path.join(dir, file), 'utf8');
  const h1 = src.match(/<h1[^>]*>([\s\S]*?)<\/h1>/);
  const title = h1 ? stripEmoji(h1[1].replace(/<[^>]+>/g, '').replace(/\s+/g, ' ')) : '';
  const step = src.match(/שלב\s+(\S+)\s+מתוך/);
  const p = parseName(file);
  let label;
  if (step) label = 'שלב ' + step[1];
  else if (p && p.sub) label = 'שלב ' + p.num + String.fromCharCode(96 + p.sub);
  else label = '';
  return { title, label };
}

function buildProject(dir) {
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.dc.html') && parseName(f))
    .sort((a, b) => {
      const x = parseName(a), y = parseName(b);
      return x.tier - y.tier || x.num - y.num || x.sub - y.sub;
    });

  const nav = {};
  const labels = {};
  const byTier = {};
  for (const f of files) byTier[parseName(f).tier] = (byTier[parseName(f).tier] || []).concat(f);

  for (const [tier, chain] of Object.entries(byTier)) {
    // Tier 3 is a single standalone planner card — no chain, no nav.
    if (chain.length < 2) continue;
    chain.forEach((file, i) => {
      const prev = i > 0 ? chain[i - 1] : null;
      const next = i < chain.length - 1 ? chain[i + 1] : null;
      nav[file] = { prev, next };
      labels[file] = cardMeta(dir, file);
    });

    // Rewire the branch points around their optional wiring card(s). The
    // option cards are ALTERNATIVES, not a sequence: each one's prev is the
    // branch card and its next is the card after the whole branch block.
    for (const [branchFile, cfg] of Object.entries(BRANCHES)) {
      const bi = chain.indexOf(branchFile);
      if (bi === -1) continue;
      const subCards = [];
      for (let j = bi + 1; j < chain.length && parseName(chain[j]).sub > 0; j++) subCards.push(chain[j]);
      const afterBranch = chain[bi + 1 + subCards.length];
      if (!subCards.length || !afterBranch) continue;
      const firstSub = subCards[0];
      const m = {};
      const pm = {};
      for (const [opt, target] of Object.entries(cfg.options)) {
        m[opt] = target || afterBranch;
        pm[opt] = target || branchFile;
      }
      nav[branchFile].next = { k: cfg.key, m, d: firstSub };
      nav[afterBranch].prev = { k: cfg.key, m: pm, d: firstSub };
      for (const sub of subCards) nav[sub] = { prev: branchFile, next: afterBranch };
    }
  }
  return { nav, labels, files };
}

const RUNTIME = (navJson, lblJson) => `// card_nav.js — GENERATED by build_card_nav.js. Do not edit by hand;
// re-run \`node build_card_nav.js\` from the repo root instead.
//
// Adds a previous/next strip under a task card when a student views it on
// screen. Deliberately inert in three cases:
//   1. inside an iframe  — the review console renders cards in one, and extra
//      DOM would shift every blockIndex the feedback JSON records;
//   2. print media       — the PDF/HTML build renders with emulateMediaType
//      ('print'), so bundles stay exactly as they were;
//   3. @media print      — a student printing from the browser gets clean paper.
// It also mounts outside the dc React root, so a setState re-render (checkbox,
// choice) cannot drop it.
(function () {
  'use strict';
  if (window.self !== window.top) return;
  try { if (window.matchMedia && window.matchMedia('print').matches) return; } catch (e) {}

  var NAV = ${navJson};
  var LBL = ${lblJson};

  var file = '';
  try { file = decodeURIComponent(location.pathname.split('/').pop() || ''); } catch (e) { return; }
  var entry = NAV[file];
  if (!entry) return;

  function resolve(spec) {
    if (!spec) return null;
    if (typeof spec === 'string') return spec;
    var v = null;
    try { v = localStorage.getItem(spec.k); } catch (e) {}
    return (v && spec.m[v]) ? spec.m[v] : spec.d;
  }

  var prev = resolve(entry.prev);
  var next = resolve(entry.next);
  if (!prev && !next) return;

  function chip(target, kind) {
    var meta = LBL[target] || {};
    var a = document.createElement('a');
    a.className = 'cn-chip ' + (kind === 'next' ? 'cn-nx' : 'cn-pv');
    a.href = './' + target;
    var k = document.createElement('span');
    k.className = 'cn-k';
    var word = document.createElement('span');
    word.textContent = kind === 'next' ? 'הכרטיסייה הבאה' : 'הכרטיסייה הקודמת';
    var arrow = document.createElement('span');
    arrow.className = 'cn-a';
    arrow.textContent = kind === 'next' ? '\\u2190' : '\\u2192';
    if (kind === 'next') { k.appendChild(word); k.appendChild(arrow); }
    else { k.appendChild(arrow); k.appendChild(word); }
    var t = document.createElement('span');
    t.className = 'cn-t';
    t.textContent = [meta.label, meta.title].filter(Boolean).join(' · ');
    a.appendChild(k);
    a.appendChild(t);
    return a;
  }

  function mount() {
    if (document.getElementById('card-nav-root')) return;
    var css = document.createElement('style');
    css.textContent =
      '#card-nav-root{background:oklch(0.972 0.008 85);padding:0 20px 44px;display:flex;' +
      'justify-content:center;font-family:Rubik,sans-serif;}' +
      '#card-nav-root .cn-bar{width:100%;max-width:760px;display:flex;gap:14px;align-items:stretch;}' +
      '#card-nav-root .cn-chip{flex:1 1 0;display:flex;flex-direction:column;gap:4px;' +
      'text-decoration:none;background:#fff;border:1px solid oklch(0.9 0.006 85);border-radius:14px;' +
      'padding:13px 17px;box-shadow:0 1px 2px rgba(40,35,20,0.04);' +
      'transition:border-color .15s ease,box-shadow .15s ease;}' +
      '#card-nav-root .cn-chip:hover{border-color:oklch(0.62 0.1 248);' +
      'box-shadow:0 6px 18px -10px rgba(40,35,20,0.35);}' +
      '#card-nav-root .cn-pv{align-items:flex-start;}' +
      '#card-nav-root .cn-nx{align-items:flex-end;text-align:end;}' +
      '#card-nav-root .cn-gap{flex:1 1 0;}' +
      '#card-nav-root .cn-k{display:flex;align-items:center;gap:7px;font-size:12.5px;' +
      'font-weight:600;color:oklch(0.55 0.012 260);}' +
      '#card-nav-root .cn-a{font-size:15px;color:oklch(0.55 0.09 248);}' +
      '#card-nav-root .cn-t{font-size:15px;font-weight:700;line-height:1.35;' +
      'color:oklch(0.42 0.11 248);}' +
      '@media print{#card-nav-root{display:none !important;}}';
    document.head.appendChild(css);

    var root = document.createElement('div');
    root.id = 'card-nav-root';
    root.setAttribute('dir', 'rtl');
    var bar = document.createElement('nav');
    bar.className = 'cn-bar';
    bar.setAttribute('aria-label', 'ניווט בין כרטיסיות');
    // DOM order is prev-then-next; in RTL that puts הקודמת on the right.
    if (prev) bar.appendChild(chip(prev, 'prev'));
    else { var g1 = document.createElement('span'); g1.className = 'cn-gap'; bar.appendChild(g1); }
    if (next) bar.appendChild(chip(next, 'next'));
    else { var g2 = document.createElement('span'); g2.className = 'cn-gap'; bar.appendChild(g2); }
    root.appendChild(bar);
    document.body.appendChild(root);
  }

  // Wait for the dc runtime to paint the card so the strip lands under it.
  var t0 = Date.now();
  (function wait() {
    if (document.querySelector('.tc-page') || Date.now() - t0 > 4000) { mount(); return; }
    setTimeout(wait, 60);
  })();
})();
`;

const TAG = '<script src="./card_nav.js"></script>';
const check = process.argv.includes('--check');
let wrote = 0, tagged = 0, problems = [];

for (const proj of PROJECTS) {
  const dir = path.join(ROOT, proj, 'task_cards_he');
  if (!fs.existsSync(dir)) { problems.push('missing dir: ' + dir); continue; }
  const { nav, labels, files } = buildProject(dir);

  // Every target must exist on disk.
  for (const [from, e] of Object.entries(nav)) {
    for (const spec of [e.prev, e.next]) {
      const targets = !spec ? [] : typeof spec === 'string' ? [spec] : [spec.d, ...Object.values(spec.m)];
      for (const t of targets) {
        if (!fs.existsSync(path.join(dir, t))) problems.push(`${proj}/${from}: target missing -> ${t}`);
      }
    }
  }

  const out = RUNTIME(JSON.stringify(nav, null, 0), JSON.stringify(labels, null, 0));
  const outPath = path.join(dir, 'card_nav.js');
  const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;
  if (existing !== out) {
    if (check) problems.push(`${proj}/card_nav.js is stale`);
    else { fs.writeFileSync(outPath, out); wrote++; }
  }

  for (const f of files) {
    const p = path.join(dir, f);
    let src = fs.readFileSync(p, 'utf8');
    if (src.includes(TAG)) continue;
    if (!src.includes('<script src="./support.js"></script>')) {
      problems.push(`${proj}/${f}: no support.js tag to anchor to`);
      continue;
    }
    if (check) { problems.push(`${proj}/${f} is missing the card_nav.js tag`); continue; }
    src = src.replace('<script src="./support.js"></script>', '<script src="./support.js"></script>\n' + TAG);
    fs.writeFileSync(p, src);
    tagged++;
  }

  const withNav = Object.keys(nav).length;
  console.log(`${proj}: ${files.length} cards, ${withNav} with nav, ${files.length - withNav} standalone`);
}

if (problems.length) {
  console.error('\nPROBLEMS:');
  for (const p of problems) console.error('  - ' + p);
  process.exit(1);
}
console.log(`\nOK — card_nav.js written: ${wrote}, cards tagged: ${tagged}`);
